In [1]:
from pathlib import Path

import pandas as pd

In [2]:
project_dir = Path.cwd()

if project_dir.name == "notebooks":
    project_dir = project_dir.parent

In [3]:
raw_data_path = (
    project_dir
    / "data"
    / "raw"
    / "apartments_pl_2023_08.csv"
)

df = pd.read_csv(raw_data_path)

In [4]:
df.head()

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,pharmacyDistance,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,blockOfFlats,63.00,3.0,4.0,10.0,1980.0,53.378933,14.625296,...,0.413,condominium,concreteSlab,NaN,yes,yes,yes,no,yes,415000
1,accbe77d4b360fea9735f138a50608dd,szczecin,blockOfFlats,36.00,2.0,8.0,10.0,NaN,53.442692,14.559690,...,0.205,cooperative,concreteSlab,NaN,no,yes,yes,no,yes,395995
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,tenement,73.02,3.0,2.0,3.0,NaN,53.452222,14.553333,...,0.280,condominium,brick,NaN,no,no,no,no,no,565000
3,0a68cd14c44ec5140143ece75d739535,szczecin,tenement,87.60,3.0,2.0,3.0,NaN,53.435100,14.532900,...,0.087,condominium,brick,NaN,yes,yes,no,no,yes,640000
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,blockOfFlats,66.00,3.0,1.0,3.0,NaN,53.410278,14.503611,...,0.514,condominium,NaN,NaN,no,no,no,no,no,759000

In [5]:
df.shape

(18905, 28)

In [6]:
df.columns

Index(['id', 'city', 'type', 'squareMeters', 'rooms', 'floor', 'floorCount',
       'buildYear', 'latitude', 'longitude', 'centreDistance', 'poiCount',
       'schoolDistance', 'clinicDistance', 'postOfficeDistance',
       'kindergartenDistance', 'restaurantDistance', 'collegeDistance',
       'pharmacyDistance', 'ownership', 'buildingMaterial', 'condition',
       'hasParkingSpace', 'hasBalcony', 'hasElevator', 'hasSecurity',
       'hasStorageRoom', 'price'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18905 entries, 0 to 18904
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    18905 non-null  str
 1   city                  18905 non-null  str
 2   type                  14866 non-null  str
 3   squareMeters          18905 non-null  float64
 4   rooms                 18905 non-null  float64
 5   floor                 15467 non-null  float64
 6   floorCount            18643 non-null  float64
 7   buildYear             15634 non-null  float64
 8   latitude              18905 non-null  float64
 9   longitude             18905 non-null  float64
 10  centreDistance        18905 non-null  float64
 11  poiCount              18905 non-null  float64
 12  schoolDistance        18891 non-null  float64
 13  clinicDistance        18817 non-null  float64
 14  postOfficeDistance    18880 non-null  float64
 15  kindergartenDistance  18892 non-null  float64
 16  restaurantDistance    18847 non-null  float64
 17  collegeDistance       18340 non-null  float64
 18  pharmacyDistance      18878 non-null  float64
 19  ownership             18905 non-null  str
 20  buildingMaterial      11518 non-null  str
 21  condition             4561 non-null   str
 22  hasParkingSpace       18905 non-null  str
 23  hasBalcony            18905 non-null  str
 24  hasElevator           17979 non-null  str
 25  hasSecurity           18905 non-null  str
 26  hasStorageRoom        18905 non-null  str
 27  price                 18905 non-null  int64
dtypes: float64(16), int64(1), str(11)
memory usage: 4.0 MB

In [8]:
df.isna()

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,pharmacyDistance,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18900,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
18901,False,False,False,False,False,True,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
18902,False,False,True,False,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
18903,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18904,False,False,True,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False

In [9]:
df.isna().sum()

id                          0
city                        0
type                     4039
squareMeters                0
rooms                       0
floor                    3438
floorCount                262
buildYear                3271
latitude                    0
longitude                   0
centreDistance              0
poiCount                    0
schoolDistance             14
clinicDistance             88
postOfficeDistance         25
kindergartenDistance       13
restaurantDistance         58
collegeDistance           565
pharmacyDistance           27
ownership                   0
buildingMaterial         7387
condition               14344
hasParkingSpace             0
hasBalcony                  0
hasElevator               926
hasSecurity                 0
hasStorageRoom              0
price                       0
dtype: int64

In [10]:
df.isna().sum().sort_values(ascending=False)

condition               14344
buildingMaterial         7387
type                     4039
floor                    3438
buildYear                3271
hasElevator               926
collegeDistance           565
floorCount                262
clinicDistance             88
restaurantDistance         58
pharmacyDistance           27
postOfficeDistance         25
schoolDistance             14
kindergartenDistance       13
longitude                   0
latitude                    0
rooms                       0
id                          0
city                        0
squareMeters                0
poiCount                    0
centreDistance              0
ownership                   0
hasParkingSpace             0
hasBalcony                  0
hasSecurity                 0
hasStorageRoom              0
price                       0
dtype: int64

In [11]:
df.isna().mean()

id                      0.000000
city                    0.000000
type                    0.213647
squareMeters            0.000000
rooms                   0.000000
floor                   0.181857
floorCount              0.013859
buildYear               0.173023
latitude                0.000000
longitude               0.000000
centreDistance          0.000000
poiCount                0.000000
schoolDistance          0.000741
clinicDistance          0.004655
postOfficeDistance      0.001322
kindergartenDistance    0.000688
restaurantDistance      0.003068
collegeDistance         0.029886
pharmacyDistance        0.001428
ownership               0.000000
buildingMaterial        0.390743
condition               0.758741
hasParkingSpace         0.000000
hasBalcony              0.000000
hasElevator             0.048982
hasSecurity             0.000000
hasStorageRoom          0.000000
price                   0.000000
dtype: float64

In [12]:
df.isna().mean().mul(100).sort_values(ascending=False)

condition               75.874107
buildingMaterial        39.074319
type                    21.364718
floor                   18.185665
buildYear               17.302301
hasElevator              4.898175
collegeDistance          2.988627
floorCount               1.385877
clinicDistance           0.465485
restaurantDistance       0.306797
pharmacyDistance         0.142819
postOfficeDistance       0.132240
schoolDistance           0.074054
kindergartenDistance     0.068765
longitude                0.000000
latitude                 0.000000
rooms                    0.000000
id                       0.000000
city                     0.000000
squareMeters             0.000000
poiCount                 0.000000
centreDistance           0.000000
ownership                0.000000
hasParkingSpace          0.000000
hasBalcony               0.000000
hasSecurity              0.000000
hasStorageRoom           0.000000
price                    0.000000
dtype: float64

In [13]:
selected_columns = ["id", "city", "squareMeters", "rooms", "floor", "floorCount", "buildYear", "hasParkingSpace", "hasBalcony", "hasElevator", "price"]

In [14]:
apartments_df = df[selected_columns].copy()

In [15]:
apartments_df.head()

,id,city,squareMeters,rooms,floor,floorCount,buildYear,hasParkingSpace,hasBalcony,hasElevator,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,63.00,3.0,4.0,10.0,1980.0,yes,yes,yes,415000
1,accbe77d4b360fea9735f138a50608dd,szczecin,36.00,2.0,8.0,10.0,NaN,no,yes,yes,395995
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,73.02,3.0,2.0,3.0,NaN,no,no,no,565000
3,0a68cd14c44ec5140143ece75d739535,szczecin,87.60,3.0,2.0,3.0,NaN,yes,yes,no,640000
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,66.00,3.0,1.0,3.0,NaN,no,no,no,759000

In [16]:
apartments_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18905 entries, 0 to 18904
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               18905 non-null  str
 1   city             18905 non-null  str
 2   squareMeters     18905 non-null  float64
 3   rooms            18905 non-null  float64
 4   floor            15467 non-null  float64
 5   floorCount       18643 non-null  float64
 6   buildYear        15634 non-null  float64
 7   hasParkingSpace  18905 non-null  str
 8   hasBalcony       18905 non-null  str
 9   hasElevator      17979 non-null  str
 10  price            18905 non-null  int64
dtypes: float64(5), int64(1), str(5)
memory usage: 1.6 MB

In [17]:
apartments_df.isna().mean().mul(100)

id                  0.000000
city                0.000000
squareMeters        0.000000
rooms               0.000000
floor              18.185665
floorCount          1.385877
buildYear          17.302301
hasParkingSpace     0.000000
hasBalcony          0.000000
hasElevator         4.898175
price               0.000000
dtype: float64

In [18]:
missing_floor = apartments_df["floor"].isna()

In [19]:
apartments_df[missing_floor]

,id,city,squareMeters,rooms,floor,floorCount,buildYear,hasParkingSpace,hasBalcony,hasElevator,price
11,ddff3f0ed9bb278617b6165aee8ab26c,szczecin,63.90,3.0,NaN,4.0,2000.0,no,yes,no,545000
13,9ebbaddd05ba76b732e7e4d99c2e3509,szczecin,95.78,4.0,NaN,4.0,1945.0,no,no,no,649000
30,efbd05715f9592339f2aee02017a77a6,szczecin,44.60,2.0,NaN,3.0,2016.0,no,no,no,475000
35,355336466ec74696782ce382341086bd,szczecin,58.60,2.0,NaN,4.0,NaN,no,no,no,479000
38,98e40021de61a29b10f347c66744b51e,szczecin,92.32,3.0,NaN,2.0,1920.0,yes,no,no,489000
...,...,...,...,...,...,...,...,...,...,...,...
18891,152dbb59ed1105801ae7d23cda0a64f3,bydgoszcz,68.00,2.0,NaN,NaN,NaN,no,no,NaN,335000
18896,252d9a7cfee03c757c16ee6a98228327,bydgoszcz,93.30,4.0,NaN,2.0,1937.0,no,no,no,469900
18898,b54751e18d2395c2ad51071951bec6f5,bydgoszcz,47.00,2.0,NaN,1.0,NaN,no,no,no,260000
18900,ae88d7ea0a7a5fa0e9d287cfd78e5676,bydgoszcz,84.00,3.0,NaN,4.0,2000.0,yes,yes,no,789000
18901,6a4b30b5fcdee00bfe5bcc0da82df9b1,bydgoszcz,94.30,4.0,NaN,2.0,1998.0,no,yes,no,699000

In [20]:
apartments_df[missing_floor].shape

(3438, 11)

In [21]:
apartments_df["id"].duplicated().sum()

np.int64(0)

In [22]:
apartments_df.duplicated().sum()

np.int64(0)

In [23]:
numeric_columns = ["squareMeters", "rooms", "floor", "floorCount", "buildYear", "price", ]

In [24]:
apartments_df[numeric_columns].describe()

,squareMeters,rooms,floor,floorCount,buildYear,price
count,18905.000000,18905.000000,15467.000000,18643.000000,15634.000000,1.890500e+04
mean,58.509976,2.676752,3.339820,5.279783,1984.551043,6.925592e+05
std,21.060168,0.903619,2.549141,3.333666,33.767929,3.443890e+05
min,25.000000,1.000000,1.000000,1.000000,1850.000000,1.500000e+05
25%,44.200000,2.000000,2.000000,3.000000,1967.000000,4.588000e+05
50%,54.400000,3.000000,3.000000,4.000000,1990.000000,6.200000e+05
75%,68.200000,3.000000,4.000000,6.000000,2014.000000,8.300000e+05
max,150.000000,6.000000,29.000000,29.000000,2023.000000,2.500000e+06

In [25]:
apartments_df["city"].nunique()

15

In [26]:
apartments_df["city"].value_counts()

city
warszawa       5471
krakow         2983
gdansk         1898
wroclaw        1768
lodz           1555
bydgoszcz       941
gdynia          830
poznan          773
lublin          691
szczecin        552
katowice        488
radom           324
bialystok       262
rzeszow         194
czestochowa     175
Name: count, dtype: int64

In [27]:
apartments_df["hasBalcony"].value_counts(dropna=False)

hasBalcony
yes    10864
no      8041
Name: count, dtype: int64

In [28]:
apartments_df["hasParkingSpace"].value_counts(dropna=False)

hasParkingSpace
no     14017
yes     4888
Name: count, dtype: int64

In [29]:
apartments_df["hasElevator"].value_counts(dropna=False)

hasElevator
no     9510
yes    8469
NaN     926
Name: count, dtype: int64

In [30]:
apartments_df["hasBalcony"] = apartments_df["hasBalcony"].map({"yes": True, "no": False})

In [31]:
apartments_df["hasBalcony"].value_counts(dropna=False)

hasBalcony
True     10864
False     8041
Name: count, dtype: int64

In [32]:
apartments_df["hasBalcony"].dtype

dtype('bool')

In [33]:
apartments_df["hasParkingSpace"] = apartments_df["hasParkingSpace"].map({"no": False, "yes": True})

In [34]:
apartments_df["hasParkingSpace"].value_counts(dropna=False)

hasParkingSpace
False    14017
True      4888
Name: count, dtype: int64

In [35]:
apartments_df["hasElevator"] = (apartments_df["hasElevator"].map({"no": False, "yes": True}).astype("boolean"))

In [36]:
apartments_df

,id,city,squareMeters,rooms,floor,floorCount,buildYear,hasParkingSpace,hasBalcony,hasElevator,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,63.00,3.0,4.0,10.0,1980.0,True,True,True,415000
1,accbe77d4b360fea9735f138a50608dd,szczecin,36.00,2.0,8.0,10.0,NaN,False,True,True,395995
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,73.02,3.0,2.0,3.0,NaN,False,False,False,565000
3,0a68cd14c44ec5140143ece75d739535,szczecin,87.60,3.0,2.0,3.0,NaN,True,True,False,640000
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,66.00,3.0,1.0,3.0,NaN,False,False,False,759000
...,...,...,...,...,...,...,...,...,...,...,...
18900,ae88d7ea0a7a5fa0e9d287cfd78e5676,bydgoszcz,84.00,3.0,NaN,4.0,2000.0,True,True,False,789000
18901,6a4b30b5fcdee00bfe5bcc0da82df9b1,bydgoszcz,94.30,4.0,NaN,2.0,1998.0,False,True,False,699000
18902,1e7f4f1fdfea31eb84e071d697839632,bydgoszcz,50.12,2.0,1.0,1.0,NaN,True,False,False,360000
18903,d971c4ed3aab9919bf203e96019a678e,bydgoszcz,100.00,4.0,3.0,4.0,1910.0,True,True,False,590000
18904,cd0241b70b79aaaf767a0dd3a7cfbb31,bydgoszcz,81.07,5.0,1.0,4.0,2019.0,False,True,True,699000

In [37]:
apartments_df["hasElevator"].value_counts(dropna=False)

hasElevator
False    9510
True     8469
<NA>      926
Name: count, dtype: Int64

In [38]:
apartments_df["hasElevator"].dtype

BooleanDtype

In [39]:
column_names = {
    "id": "source_id",
    "squareMeters": "area",
    "floorCount": "floor_count",
    "buildYear": "year_built",
    "hasParkingSpace": "has_parking",
    "hasBalcony": "has_balcony",
    "hasElevator": "has_elevator",
}

In [40]:
apartments_df = apartments_df.rename(columns=column_names)

In [41]:
apartments_df.head()

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,63.00,3.0,4.0,10.0,1980.0,True,True,True,415000
1,accbe77d4b360fea9735f138a50608dd,szczecin,36.00,2.0,8.0,10.0,NaN,False,True,True,395995
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,73.02,3.0,2.0,3.0,NaN,False,False,False,565000
3,0a68cd14c44ec5140143ece75d739535,szczecin,87.60,3.0,2.0,3.0,NaN,True,True,False,640000
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,66.00,3.0,1.0,3.0,NaN,False,False,False,759000

In [42]:
apartments_df["city"] = apartments_df["city"].str.title()

In [43]:
apartments_df.head()

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,Szczecin,63.00,3.0,4.0,10.0,1980.0,True,True,True,415000
1,accbe77d4b360fea9735f138a50608dd,Szczecin,36.00,2.0,8.0,10.0,NaN,False,True,True,395995
2,8373aa373dbc3fe7ca3b7434166b8766,Szczecin,73.02,3.0,2.0,3.0,NaN,False,False,False,565000
3,0a68cd14c44ec5140143ece75d739535,Szczecin,87.60,3.0,2.0,3.0,NaN,True,True,False,640000
4,f66320e153c2441edc0fe293b54c8aeb,Szczecin,66.00,3.0,1.0,3.0,NaN,False,False,False,759000

In [44]:
apartments_df["city"].value_counts()

city
Warszawa       5471
Krakow         2983
Gdansk         1898
Wroclaw        1768
Lodz           1555
Bydgoszcz       941
Gdynia          830
Poznan          773
Lublin          691
Szczecin        552
Katowice        488
Radom           324
Bialystok       262
Rzeszow         194
Czestochowa     175
Name: count, dtype: int64

In [45]:
city_names = {
    "Krakow": "Kraków",
    "Gdansk": "Gdańsk",
    "Wroclaw": "Wrocław",
    "Lodz": "Łódź",
    "Poznan": "Poznań",
    "Bialystok": "Białystok",
    "Czestochowa": "Częstochowa",
}

In [46]:
apartments_df["city"] = apartments_df["city"].replace(city_names)

In [47]:
apartments_df["city"].value_counts()

city
Warszawa       5471
Kraków         2983
Gdańsk         1898
Wrocław        1768
Łódź           1555
Bydgoszcz       941
Gdynia          830
Poznań          773
Lublin          691
Szczecin        552
Katowice        488
Radom           324
Białystok       262
Rzeszow         194
Częstochowa     175
Name: count, dtype: int64

In [48]:
city_names = {
    "Rzeszow": "Rzeszów"
}

In [49]:
apartments_df["city"] = apartments_df["city"].replace(city_names)

In [50]:
apartments_df["city"].value_counts()

city
Warszawa       5471
Kraków         2983
Gdańsk         1898
Wrocław        1768
Łódź           1555
Bydgoszcz       941
Gdynia          830
Poznań          773
Lublin          691
Szczecin        552
Katowice        488
Radom           324
Białystok       262
Rzeszów         194
Częstochowa     175
Name: count, dtype: int64

In [51]:
apartments_df.head()

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,Szczecin,63.00,3.0,4.0,10.0,1980.0,True,True,True,415000
1,accbe77d4b360fea9735f138a50608dd,Szczecin,36.00,2.0,8.0,10.0,NaN,False,True,True,395995
2,8373aa373dbc3fe7ca3b7434166b8766,Szczecin,73.02,3.0,2.0,3.0,NaN,False,False,False,565000
3,0a68cd14c44ec5140143ece75d739535,Szczecin,87.60,3.0,2.0,3.0,NaN,True,True,False,640000
4,f66320e153c2441edc0fe293b54c8aeb,Szczecin,66.00,3.0,1.0,3.0,NaN,False,False,False,759000

In [52]:
apartments_df["rooms"] = apartments_df["rooms"].astype("int64")

In [53]:
apartments_df.head()

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,Szczecin,63.00,3,4.0,10.0,1980.0,True,True,True,415000
1,accbe77d4b360fea9735f138a50608dd,Szczecin,36.00,2,8.0,10.0,NaN,False,True,True,395995
2,8373aa373dbc3fe7ca3b7434166b8766,Szczecin,73.02,3,2.0,3.0,NaN,False,False,False,565000
3,0a68cd14c44ec5140143ece75d739535,Szczecin,87.60,3,2.0,3.0,NaN,True,True,False,640000
4,f66320e153c2441edc0fe293b54c8aeb,Szczecin,66.00,3,1.0,3.0,NaN,False,False,False,759000

In [54]:
apartments_df["floor"] = apartments_df["floor"].astype("Int64")

In [55]:
apartments_df["floor_count"] = apartments_df["floor_count"].astype("Int64")

In [56]:
apartments_df["year_built"] = apartments_df["year_built"].astype("Int64")

In [57]:
apartments_df.head()

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,Szczecin,63.00,3,4,10,1980,True,True,True,415000
1,accbe77d4b360fea9735f138a50608dd,Szczecin,36.00,2,8,10,<NA>,False,True,True,395995
2,8373aa373dbc3fe7ca3b7434166b8766,Szczecin,73.02,3,2,3,<NA>,False,False,False,565000
3,0a68cd14c44ec5140143ece75d739535,Szczecin,87.60,3,2,3,<NA>,True,True,False,640000
4,f66320e153c2441edc0fe293b54c8aeb,Szczecin,66.00,3,1,3,<NA>,False,False,False,759000

In [58]:
apartments_df[
    ["rooms", "floor", "floor_count", "year_built"]
].head()

   rooms  floor  floor_count  year_built
0      3      4           10        1980
1      2      8           10        <NA>
2      3      2            3        <NA>
3      3      2            3        <NA>
4      3      1            3        <NA>

In [59]:
invalid_floor = (apartments_df["floor"].notna() & apartments_df["floor_count"].notna() & (apartments_df["floor"] < apartments_df["floor_count"]))

In [60]:
invalid_floor.sum()

np.int64(11116)

In [61]:
invalid_year = (apartments_df["year_built"].notna() & ((apartments_df["year_built"]<1851) | (apartments_df["year_built"]>2023)))

In [62]:
invalid_year.sum()

np.int64(1)

In [63]:
apartments_df[invalid_year]

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price
18238,f120f31879113098e018b97b1d7dd757,Bydgoszcz,38.0,2,<NA>,2,1850,True,False,False,265000

In [64]:
apartments_df["price_per_sqm"] = (apartments_df["price"] / apartments_df["area"])

In [65]:
apartments_df[["price", "area", "price_per_sqm"]].head().round(2)

    price   area  price_per_sqm
0  415000  63.00        6587.30
1  395995  36.00       10999.86
2  565000  73.02        7737.61
3  640000  87.60        7305.94
4  759000  66.00       11500.00

In [66]:
apartments_df[["price", "area", "price_per_sqm"]].head().round(2)

    price   area  price_per_sqm
0  415000  63.00        6587.30
1  395995  36.00       10999.86
2  565000  73.02        7737.61
3  640000  87.60        7305.94
4  759000  66.00       11500.00

In [67]:
apartments_df["price_per_sqm"].describe().round(2)

count    18905.00
mean     12007.83
std       4353.10
min       3011.63
25%       8805.19
50%      11383.20
75%      14467.23
max      29995.10
Name: price_per_sqm, dtype: float64

In [68]:
city_median_price = (apartments_df.groupby("city")["price_per_sqm"].median().sort_values(ascending=False).round(2))

In [69]:
city_median_price

city
Warszawa       14713.13
Kraków         13001.32
Gdańsk         12098.58
Wrocław        11209.01
Gdynia         10583.41
Poznań          9791.67
Rzeszów         9226.70
Lublin          8491.30
Białystok       8150.58
Szczecin        7989.85
Łódź            7450.11
Katowice        7326.06
Bydgoszcz       7306.93
Radom           6140.23
Częstochowa     5948.55
Name: price_per_sqm, dtype: float64

In [70]:
apartments_df["city_median_price_per_sqm"] = (apartments_df.groupby("city")["price_per_sqm"].transform("median"))

In [71]:
apartments_df[
["city", "price_per_sqm", "city_median_price_per_sqm"]
].head(10).round(2)

       city  price_per_sqm  city_median_price_per_sqm
0  Szczecin        6587.30                    7989.85
1  Szczecin       10999.86                    7989.85
2  Szczecin        7737.61                    7989.85
3  Szczecin        7305.94                    7989.85
4  Szczecin       11500.00                    7989.85
5  Szczecin        7883.10                    7989.85
6  Szczecin        7797.68                    7989.85
7  Szczecin       10469.37                    7989.85
8  Szczecin        8354.27                    7989.85
9  Szczecin        4508.25                    7989.85

In [72]:
apartments_df["city"] == "Warszawa"

0        False
1        False
2        False
3        False
4        False
         ...
18900    False
18901    False
18902    False
18903    False
18904    False
Name: city, Length: 18905, dtype: bool

In [73]:
apartments_df

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price,price_per_sqm,city_median_price_per_sqm
0,f8524536d4b09a0c8ccc0197ec9d7bde,Szczecin,63.00,3,4,10,1980,True,True,True,415000,6587.301587,7989.845361
1,accbe77d4b360fea9735f138a50608dd,Szczecin,36.00,2,8,10,<NA>,False,True,True,395995,10999.861111,7989.845361
2,8373aa373dbc3fe7ca3b7434166b8766,Szczecin,73.02,3,2,3,<NA>,False,False,False,565000,7737.606135,7989.845361
3,0a68cd14c44ec5140143ece75d739535,Szczecin,87.60,3,2,3,<NA>,True,True,False,640000,7305.936073,7989.845361
4,f66320e153c2441edc0fe293b54c8aeb,Szczecin,66.00,3,1,3,<NA>,False,False,False,759000,11500.000000,7989.845361
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18900,ae88d7ea0a7a5fa0e9d287cfd78e5676,Bydgoszcz,84.00,3,<NA>,4,2000,True,True,False,789000,9392.857143,7306.930693
18901,6a4b30b5fcdee00bfe5bcc0da82df9b1,Bydgoszcz,94.30,4,<NA>,2,1998,False,True,False,699000,7412.513256,7306.930693
18902,1e7f4f1fdfea31eb84e071d697839632,Bydgoszcz,50.12,2,1,1,<NA>,True,False,False,360000,7182.761373,7306.930693
18903,d971c4ed3aab9919bf203e96019a678e,Bydgoszcz,100.00,4,3,4,1910,True,True,False,590000,5900.000000,7306.930693
18904,cd0241b70b79aaaf767a0dd3a7cfbb31,Bydgoszcz,81.07,5,1,4,2019,False,True,True,699000,8622.178364,7306.930693

In [74]:
apartments_df["price_difference_pct"] = ((apartments_df["price_per_sqm"] / apartments_df["city_median_price_per_sqm"])-1)*100

In [75]:
apartments_df[["city", "price_per_sqm", "city_median_price_per_sqm", "price_difference_pct"]].head(10).round(2)

       city  price_per_sqm  city_median_price_per_sqm  price_difference_pct
0  Szczecin        6587.30                    7989.85                -17.55
1  Szczecin       10999.86                    7989.85                 37.67
2  Szczecin        7737.61                    7989.85                 -3.16
3  Szczecin        7305.94                    7989.85                 -8.56
4  Szczecin       11500.00                    7989.85                 43.93
5  Szczecin        7883.10                    7989.85                 -1.34
6  Szczecin        7797.68                    7989.85                 -2.41
7  Szczecin       10469.37                    7989.85                 31.03
8  Szczecin        8354.27                    7989.85                  4.56
9  Szczecin        4508.25                    7989.85                -43.58

In [76]:
def classify_offer(price_difference):
    if price_difference < -10:
        return "Atrakcyjna"
    elif price_difference <= 10:
        return "W średniej"
    else:
        return "Powyżej średniej"

In [77]:
apartments_df["price_rating"] = apartments_df["price_difference_pct"].apply(classify_offer)

In [78]:
apartments_df[["city", "price_difference_pct", "price_rating"]].head(10).round(2)

       city  price_difference_pct      price_rating
0  Szczecin                -17.55        Atrakcyjna
1  Szczecin                 37.67  Powyżej średniej
2  Szczecin                 -3.16        W średniej
3  Szczecin                 -8.56        W średniej
4  Szczecin                 43.93  Powyżej średniej
5  Szczecin                 -1.34        W średniej
6  Szczecin                 -2.41        W średniej
7  Szczecin                 31.03  Powyżej średniej
8  Szczecin                  4.56        W średniej
9  Szczecin                -43.58        Atrakcyjna

In [79]:
apartments_df["price_rating"].value_counts()

price_rating
Powyżej średniej    6427
W średniej          6381
Atrakcyjna          6097
Name: count, dtype: int64

In [80]:
apartments_df["price_rating"].value_counts(normalize=True).mul(100).round(2)

price_rating
Powyżej średniej    34.00
W średniej          33.75
Atrakcyjna          32.25
Name: proportion, dtype: float64

In [81]:
apartments_df["price_rating"].isna().sum()

np.int64(0)

In [82]:
apartments_df.isna().sum().sort_values(ascending=False)

floor                        3438
year_built                   3271
has_elevator                  926
floor_count                   262
area                            0
source_id                       0
city                            0
rooms                           0
has_parking                     0
has_balcony                     0
price                           0
price_per_sqm                   0
city_median_price_per_sqm       0
price_difference_pct            0
price_rating                    0
dtype: int64

In [83]:
processed_dir = project_dir / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

In [84]:
processed_dir.exists()

True

In [85]:
output_path = processed_dir / "apartments_cleaned.csv"

apartments_df.to_csv(output_path, index=False, encoding='utf-8',)

In [86]:
output_path.exists()

True

In [87]:
cleaned_df = pd.read_csv(output_path)

In [88]:
cleaned_df

,source_id,city,area,rooms,floor,floor_count,year_built,has_parking,has_balcony,has_elevator,price,price_per_sqm,city_median_price_per_sqm,price_difference_pct,price_rating
0,f8524536d4b09a0c8ccc0197ec9d7bde,Szczecin,63.00,3,4.0,10.0,1980.0,True,True,True,415000,6587.301587,7989.845361,-17.554079,Atrakcyjna
1,accbe77d4b360fea9735f138a50608dd,Szczecin,36.00,2,8.0,10.0,NaN,False,True,True,395995,10999.861111,7989.845361,37.673016,Powyżej średniej
2,8373aa373dbc3fe7ca3b7434166b8766,Szczecin,73.02,3,2.0,3.0,NaN,False,False,False,565000,7737.606135,7989.845361,-3.156998,W średniej
3,0a68cd14c44ec5140143ece75d739535,Szczecin,87.60,3,2.0,3.0,NaN,True,True,False,640000,7305.936073,7989.845361,-8.559731,W średniej
4,f66320e153c2441edc0fe293b54c8aeb,Szczecin,66.00,3,1.0,3.0,NaN,False,False,False,759000,11500.000000,7989.845361,43.932698,Powyżej średniej
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18900,ae88d7ea0a7a5fa0e9d287cfd78e5676,Bydgoszcz,84.00,3,NaN,4.0,2000.0,True,True,False,789000,9392.857143,7306.930693,28.547232,Powyżej średniej
18901,6a4b30b5fcdee00bfe5bcc0da82df9b1,Bydgoszcz,94.30,4,NaN,2.0,1998.0,False,True,False,699000,7412.513256,7306.930693,1.444965,W średniej
18902,1e7f4f1fdfea31eb84e071d697839632,Bydgoszcz,50.12,2,1.0,1.0,NaN,True,False,False,360000,7182.761373,7306.930693,-1.699336,W średniej
18903,d971c4ed3aab9919bf203e96019a678e,Bydgoszcz,100.00,4,3.0,4.0,1910.0,True,True,False,590000,5900.000000,7306.930693,-19.254743,Atrakcyjna
18904,cd0241b70b79aaaf767a0dd3a7cfbb31,Bydgoszcz,81.07,5,1.0,4.0,2019.0,False,True,True,699000,8622.178364,7306.930693,18.000002,Powyżej średniej

In [89]:
cleaned_df.columns

Index(['source_id', 'city', 'area', 'rooms', 'floor', 'floor_count',
       'year_built', 'has_parking', 'has_balcony', 'has_elevator', 'price',
       'price_per_sqm', 'city_median_price_per_sqm', 'price_difference_pct',
       'price_rating'],
      dtype='str')

In [90]:
cleaned_df[
    ["price_per_sqm", "city_median_price_per_sqm", "price_difference_pct"]
].describe().round(2)

       price_per_sqm  city_median_price_per_sqm  price_difference_pct
count       18905.00                   18905.00              18905.00
mean        12007.83                   11514.52                  4.11
std          4353.10                    2809.70                 25.61
min          3011.63                    5948.55                -58.89
25%          8805.19                    8491.30                -14.38
50%         11383.20                   12098.58                  0.00
75%         14467.23                   14713.13                 17.88
max         29995.10                   14713.13                106.64